// A single image consists of URL for 3 images
// src: full-sized original
// collageSrc: mid-sized for display in collage or collection views
// navSrc: small-sized for navigation buttons
export interface PostImage {
    src: string;
    collageSrc: string;
    navSrc: string;
}

// Data collections define
// Typically generated by "npm run gen-collections"
export interface Collection {
    id: string;
    title: string;
    subtitle: string;
    sortDate: string;
    forceFirstTitleImage: number;
    titleImages: PostImage[];
    parent: string;
    posts: string[];
}

// Content of a single post
// Typically generated by "post-gen" page
export interface Post {
    id: string;
    date: string;
    collection: string;
    title: string;
    content: string;
    contentParagraphs: string[] | undefined; // generated
    images: PostImage[];
}